from glob import glob
import os
from typing import List


def script_dir():
    return os.path.dirname(__file__)


def collect_anims():
    anim_file_pattern = os.path.join(script_dir(), "*.json")
    return [os.path.splitext(os.path.basename(anim_file))[0]
            for anim_file in glob(anim_file_pattern)]


def generate_script(anims: List[str]):
    imports = "\n".join(f'import {anim} from "dataurl:./{anim}.json";' for anim in anims)
    exports = "\n".join(f'    {anim}: {anim} as string' for anim in anims)
    return f"""// AUTOGENERATED FILE - DO NOT MODIFY
// @ts-nocheck

{imports}

export default {{
{exports}
}};
"""


def write_script(contents: str):
    with open(os.path.join(script_dir(), "index.ts"), "w") as fp:
        fp.write(contents)


def main():
    anims = collect_anims()
    script = generate_script(anims)
    write_script(script)


if __name__ == "__main__":
    main()
